name: CI
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  generate-matrix:
    name: Generate matrix from cabal
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract the tested GHC versions
        id: set-matrix
        uses: kleidukos/get-tested@v0.1.7.0
        with:
          cabal-file: primesieve.cabal
          ubuntu-version: latest
          version: 0.1.7.0
  cabal_build:
    name: cabal build - ghc-${{ matrix.ghc }}
    needs: generate-matrix
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}
      - run: sudo apt-get install -y libprimesieve-dev
      - name: Run cabal configure
        run: cabal configure --allow-newer
      - run: cabal update
      - run: cabal outdated --exit-code
      - run: cabal freeze
      - run: cabal build
